name: open_password_manager
description: "Open source password manager tool"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: 3.35.3

dependencies:
  flutter:
    sdk: flutter

  appwrite: ^17.0.1
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.0
  connectivity_plus: ^6.1.5
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  file_picker: ^10.2.2
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_core_web: ^3.0.0
  firebase_crashlytics: ^5.0.0
  flutter_secure_storage: ^9.2.4
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  local_auth: ^2.3.0
  local_auth_android: ^1.0.51
  local_auth_darwin: ^1.6.0
  local_auth_windows: ^1.0.11
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  pointycastle: ^4.0.0
  shadcn_ui: ^0.28.1
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.9.1
  timeago: ^3.7.1
  uuid: ^4.5.1
  url_launcher: ^6.3.2
  web: ^1.1.1
  flutter_license_manager: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.6.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  mockito: ^5.5.0

flutter:
  uses-material-design: true

  assets:
    - config.json
    - images/opm-light-128.png
    - images/opm-dark-128.png
    - images/opm-splash-light.png
    - images/opm-splash-dark.png
    - images/opm-banner-light.png
    - images/opm-banner-dark.png

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/opm-dark-128.png"
  adaptive_icon_monochrome: "images/opm-dark-128.png"
  image_path_android: "images/opm-dark-128.png"
  ios: true
  image_path_ios: "images/opm-dark-128.png"
  web:
    generate: true
    image_path: "images/opm-dark-128.png"

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#FFFFFF"
  image: images/opm-splash-light.png
  color_dark: "#000000"
  image_dark: images/opm-splash-dark.png
  android_12:
    color: "#FFFFFF"
    image: images/opm-splash-light.png
    color_dark: "#000000"
    image_dark: images/opm-splash-dark.png
