name: open_password_manager
description: "Open source password manager tool"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  appwrite: ^17.0.1
  cloud_firestore: ^6.0.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_core_web: ^3.0.0
  flutter_secure_storage: ^9.2.4
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  pointycastle: ^4.0.0
  shadcn_ui: ^0.28.1
  share_plus: ^11.0.0
  supabase_flutter: ^2.9.1
  timeago: ^3.7.1
  uuid: ^4.5.1
  url_launcher: ^6.3.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  mockito: ^5.5.0
  build_runner: ^2.6.0

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - config.json
    - icons/opm-light.png
    - icons/opm-dark.png

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "icons/opm-dark.png"
  adaptive_icon_monochrome: "icons/opm-dark.png"
  image_path_android: "icons/opm-dark.png"
  web:
    generate: true
    image_path: "icons/opm-dark.png"
