name: open_password_manager
description: "Open source password managing tool"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  appwrite: ^17.0.1
  cloud_firestore: ^5.6.12
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  firebase_core_web: ^2.24.1
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  path_provider: ^2.1.3
  pointycastle: ^3.7.3
  shadcn_ui: ^0.28.1
  share_plus: ^7.2.1
  supabase_flutter: ^2.5.2
  timeago: ^3.7.1
  uuid: ^4.5.1
  url_launcher: ^6.3.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - config.json