// Mocks generated by Mockito 5.4.6 from annotations
// in open_password_manager/test/mocking/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:file_picker/file_picker.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:open_password_manager/features/auth/domain/entities/opm_user.dart'
    as _i2;
import 'package:open_password_manager/features/auth/domain/repositories/auth_repository.dart'
    as _i4;
import 'package:open_password_manager/features/auth/domain/repositories/device_auth_repository.dart'
    as _i6;
import 'package:open_password_manager/features/vault/domain/entities/vault_entry.dart'
    as _i11;
import 'package:open_password_manager/features/vault/domain/repositories/export_repository.dart'
    as _i10;
import 'package:open_password_manager/features/vault/domain/repositories/import_repository.dart'
    as _i14;
import 'package:open_password_manager/features/vault/domain/repositories/password_generator_repository.dart'
    as _i17;
import 'package:open_password_manager/features/vault/domain/repositories/vault_repository.dart'
    as _i18;
import 'package:open_password_manager/shared/application/services/storage_service.dart'
    as _i16;
import 'package:open_password_manager/shared/domain/entities/credentials.dart'
    as _i3;
import 'package:open_password_manager/shared/domain/repositories/clipboard_repository.dart'
    as _i9;
import 'package:open_password_manager/shared/domain/repositories/cryptography_repository.dart'
    as _i7;
import 'package:open_password_manager/shared/domain/repositories/salt_repository.dart'
    as _i15;
import 'package:open_password_manager/shared/utils/file_picker_service.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOpmUser_0 extends _i1.SmartFake implements _i2.OpmUser {
  _FakeOpmUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCredentials_1 extends _i1.SmartFake implements _i3.Credentials {
  _FakeCredentials_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> createAccount({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAccount, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.OpmUser> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i5.Future<_i2.OpmUser>.value(
              _FakeOpmUser_0(this, Invocation.method(#getCurrentUser, [])),
            ),
          )
          as _i5.Future<_i2.OpmUser>);
}

/// A class which mocks [DeviceAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceAuthRepository extends _i1.Mock
    implements _i6.DeviceAuthRepository {
  MockDeviceAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> isSupported() =>
      (super.noSuchMethod(
            Invocation.method(#isSupported, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.Credentials> authenticate() =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, []),
            returnValue: _i5.Future<_i3.Credentials>.value(
              _FakeCredentials_1(this, Invocation.method(#authenticate, [])),
            ),
          )
          as _i5.Future<_i3.Credentials>);

  @override
  _i5.Future<bool> hasStoredCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#hasStoredCredentials, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [CryptographyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCryptographyRepository extends _i1.Mock
    implements _i7.CryptographyRepository {
  MockCryptographyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> init(String? password, {String? sharedSalt}) =>
      (super.noSuchMethod(
            Invocation.method(#init, [password], {#sharedSalt: sharedSalt}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<String> encrypt(String? plainText) =>
      (super.noSuchMethod(
            Invocation.method(#encrypt, [plainText]),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#encrypt, [plainText]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> decrypt(String? encrypted) =>
      (super.noSuchMethod(
            Invocation.method(#decrypt, [encrypted]),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#decrypt, [encrypted]),
              ),
            ),
          )
          as _i5.Future<String>);
}

/// A class which mocks [ClipboardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockClipboardRepository extends _i1.Mock
    implements _i9.ClipboardRepository {
  MockClipboardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> copyToClipboard(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#copyToClipboard, [text]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ExportRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExportRepository extends _i1.Mock implements _i10.ExportRepository {
  MockExportRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> exportPasswordEntriesCsv(List<_i11.VaultEntry>? entries) =>
      (super.noSuchMethod(
            Invocation.method(#exportPasswordEntriesCsv, [entries]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> exportPasswordEntriesJson(List<_i11.VaultEntry>? entries) =>
      (super.noSuchMethod(
            Invocation.method(#exportPasswordEntriesJson, [entries]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [FilePickerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilePickerService extends _i1.Mock implements _i12.FilePickerService {
  MockFilePickerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i13.FilePickerResult?> pickFile() =>
      (super.noSuchMethod(
            Invocation.method(#pickFile, []),
            returnValue: _i5.Future<_i13.FilePickerResult?>.value(),
          )
          as _i5.Future<_i13.FilePickerResult?>);
}

/// A class which mocks [ImportRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockImportRepository extends _i1.Mock implements _i14.ImportRepository {
  MockImportRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void validateOpmFile(String? csvContent) => super.noSuchMethod(
    Invocation.method(#validateOpmFile, [csvContent]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i11.VaultEntry>> importFromOpm(String? csvContent) =>
      (super.noSuchMethod(
            Invocation.method(#importFromOpm, [csvContent]),
            returnValue: _i5.Future<List<_i11.VaultEntry>>.value(
              <_i11.VaultEntry>[],
            ),
          )
          as _i5.Future<List<_i11.VaultEntry>>);

  @override
  void validateBitwardenFile(String? csvContent) => super.noSuchMethod(
    Invocation.method(#validateBitwardenFile, [csvContent]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i11.VaultEntry>> importFromBitwarden(String? csvContent) =>
      (super.noSuchMethod(
            Invocation.method(#importFromBitwarden, [csvContent]),
            returnValue: _i5.Future<List<_i11.VaultEntry>>.value(
              <_i11.VaultEntry>[],
            ),
          )
          as _i5.Future<List<_i11.VaultEntry>>);

  @override
  void validate1PasswordFile(String? csvContent) => super.noSuchMethod(
    Invocation.method(#validate1PasswordFile, [csvContent]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i11.VaultEntry>> importFrom1Password(String? csvContent) =>
      (super.noSuchMethod(
            Invocation.method(#importFrom1Password, [csvContent]),
            returnValue: _i5.Future<List<_i11.VaultEntry>>.value(
              <_i11.VaultEntry>[],
            ),
          )
          as _i5.Future<List<_i11.VaultEntry>>);

  @override
  void validateLastPassFile(String? csvContent) => super.noSuchMethod(
    Invocation.method(#validateLastPassFile, [csvContent]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i11.VaultEntry>> importFromLastPass(String? csvContent) =>
      (super.noSuchMethod(
            Invocation.method(#importFromLastPass, [csvContent]),
            returnValue: _i5.Future<List<_i11.VaultEntry>>.value(
              <_i11.VaultEntry>[],
            ),
          )
          as _i5.Future<List<_i11.VaultEntry>>);

  @override
  void validateKeeperFile(String? csvContent) => super.noSuchMethod(
    Invocation.method(#validateKeeperFile, [csvContent]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i11.VaultEntry>> importFromKeeper(String? csvContent) =>
      (super.noSuchMethod(
            Invocation.method(#importFromKeeper, [csvContent]),
            returnValue: _i5.Future<List<_i11.VaultEntry>>.value(
              <_i11.VaultEntry>[],
            ),
          )
          as _i5.Future<List<_i11.VaultEntry>>);

  @override
  void validateKeepassFile(String? csvContent) => super.noSuchMethod(
    Invocation.method(#validateKeepassFile, [csvContent]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i11.VaultEntry>> importFromKeepass(String? csvContent) =>
      (super.noSuchMethod(
            Invocation.method(#importFromKeepass, [csvContent]),
            returnValue: _i5.Future<List<_i11.VaultEntry>>.value(
              <_i11.VaultEntry>[],
            ),
          )
          as _i5.Future<List<_i11.VaultEntry>>);
}

/// A class which mocks [SaltRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaltRepository extends _i1.Mock implements _i15.SaltRepository {
  MockSaltRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String?> getUserSalt(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserSalt, [userId]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> saveUserSalt(String? userId, String? salt) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserSalt, [userId, salt]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i16.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> storeAuthCredentials(_i3.Credentials? credentials) =>
      (super.noSuchMethod(
            Invocation.method(#storeAuthCredentials, [credentials]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.Credentials> loadAuthCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#loadAuthCredentials, []),
            returnValue: _i5.Future<_i3.Credentials>.value(
              _FakeCredentials_1(
                this,
                Invocation.method(#loadAuthCredentials, []),
              ),
            ),
          )
          as _i5.Future<_i3.Credentials>);
}

/// A class which mocks [PasswordGeneratorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPasswordGeneratorRepository extends _i1.Mock
    implements _i17.PasswordGeneratorRepository {
  MockPasswordGeneratorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String generatePassword(
    bool? useUppercase,
    bool? useLowercase,
    bool? useNumbers,
    bool? useSpecialChars,
    int? length,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generatePassword, [
              useUppercase,
              useLowercase,
              useNumbers,
              useSpecialChars,
              length,
            ]),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#generatePassword, [
                useUppercase,
                useLowercase,
                useNumbers,
                useSpecialChars,
                length,
              ]),
            ),
          )
          as String);
}

/// A class which mocks [VaultRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVaultRepository extends _i1.Mock implements _i18.VaultRepository {
  MockVaultRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> addEntry(_i11.VaultEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#addEntry, [entry]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> editEntry(_i11.VaultEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#editEntry, [entry]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntry, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i11.VaultEntry>> getAllEntries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEntries, []),
            returnValue: _i5.Future<List<_i11.VaultEntry>>.value(
              <_i11.VaultEntry>[],
            ),
          )
          as _i5.Future<List<_i11.VaultEntry>>);
}
