name: "Prepare Flutter"
description: "Sets up the Flutter environment, prepares the code, and validates it"

inputs:
  firebase_api_key:
    description: 'Firebase API key'
    required: true
  firebase_auth_domain:
    description: 'Firebase auth domain'
    required: true
  firebase_project_id:
    description: 'Firebase project id'
    required: true
  firebase_storage_bucket:
    description: 'Firebase storage bucket'
    required: true
  firebase_messaging_sender_id:
    description: 'Firebase messaging sender id'
    required: true
  firebase_app_id:
    description: 'Firebase app id'
    required: true
  firebase_measurement_id:
    description: 'Firebase measurement id'
    required: true
  firebase_vault_collection_prefix:
    description: 'Vault collection prefix'
    required: true
  firebase_utils_collection_name:
    description: 'Utils collection name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.35.1"
        channel: "stable"

    - name: Get packages for generator
      run: dart pub get
      shell: bash

    - name: Generate config.json
      env:
        FIREBASE_API_KEY: ${{ inputs.firebase_api_key }}
        FIREBASE_AUTH_DOMAIN: ${{ inputs.firebase_auth_domain }}
        FIREBASE_PROJECT_ID: ${{ inputs.firebase_project_id }}
        FIREBASE_STORAGE_BUCKET: ${{ inputs.firebase_storage_bucket }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ inputs.firebase_messaging_sender_id }}
        FIREBASE_APP_ID: ${{ inputs.firebase_app_id }}
        FIREBASE_MEASUREMENT_ID: ${{ inputs.firebase_measurement_id }}
        FIREBASE_VAULT_COLLECTION_PREFIX: ${{ inputs.firebase_vault_collection_prefix }}
        FIREBASE_UTILS_COLLECTION_NAME: ${{ inputs.firebase_utils_collection_name }}
      run: |
        dart run scripts/generate_config.dart config.json
      shell: bash

    - name: Get dependencies
      run: flutter pub get
      shell: bash

    - name: Analyze project
      run: flutter analyze
      shell: bash

    - name: Run tests and measure coverage
      run: |
        flutter test --coverage

        LH_TOTAL=0
        LF_TOTAL=0

        while IFS= read -r line; do
            if [[ $line == LH:* ]]; then
                LH_VALUE=${line#LH:}
                ((LH_TOTAL+=LH_VALUE))
            elif [[ $line == LF:* ]]; then
                LF_VALUE=${line#LF:}
                ((LF_TOTAL+=LF_VALUE))
            fi
        done < coverage/lcov.info

        if [[ $LF_TOTAL -gt 0 ]]; then
            TOTAL_COVERAGE=$(awk "BEGIN {printf "%.1f", ($LH_TOTAL/$LF_TOTAL)*100}")
        else
            TOTAL_COVERAGE=0
        fi

        if (( $(echo "$TOTAL_COVERAGE > 90" | bc -l) )); then
            ICON="✅✅✅"
        elif (( $(echo "$TOTAL_COVERAGE > 80" | bc -l) )); then
            ICON="✅✅"
        elif (( $(echo "$TOTAL_COVERAGE > 70" | bc -l) )); then
            ICON="✅"
        elif (( $(echo "$TOTAL_COVERAGE > 50" | bc -l) )); then
            ICON="⚠️"
        else
            ICON="❌"
        fi

        echo "$ICON Total Coverage: $TOTAL_COVERAGE%"
      shell: bash
