name: Deploy Firebase Hosting live site
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - name: Prepare Flutter
        uses: ./.github/workflows/steps/prepare-flutter
        with:
          flutter-version: '3.35.1'
          channel: 'stable'
          output-path: config.json

      - name: Build web app
        run: flutter build web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_OPM_TOOL }}
          channelId: live
          projectId: opm-tool
